services:
    eliza:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - eliza:/app/packages/client-twitter/src/tweetcache
            - eliza:/app/db.sqlite
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - USE_OPENAI_EMBEDDING=true
            - REDPILL_API_KEY=${REDPILL_API_KEY}
            - ELEVENLABS_XI_API_KEY=${ELEVENLABS_XI_API_KEY}
            - ELEVENLABS_MODEL_ID=${ELEVENLABS_MODEL_ID}
            - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
            - ELEVENLABS_VOICE_STABILITY=${ELEVENLABS_VOICE_STABILITY}
            - ELEVENLABS_VOICE_SIMILARITY_BOOST=0.9
            - ELEVENLABS_VOICE_STYLE=0.66
            - ELEVENLABS_VOICE_USE_SPEAKER_BOOST=false
            - ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=4
            - ELEVENLABS_OUTPUT_FORMAT=pcm_16000
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TWITTER_DRY_RUN=false
            - TWITTER_USERNAME=${TWITTER_USERNAME}
            - TWITTER_PASSWORD=${TWITTER_PASSWORD}
            - TWITTER_EMAIL=${TWITTER_EMAIL}
            - TWITTER_COOKIES=${TWITTER_COOKIES}
            - BIRDEYE_API_KEY=
            - SOL_ADDRESS=So11111111111111111111111111111111111111112
            - SLIPPAGE=1
            - SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
            - HELIUS_API_KEY=
            - SERVER_PORT=3000
            - WALLET_SECRET_SALT=secret_salt
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
            - MODEL_PROVIDER=anthropic
            - COINGECKO_API_KEY=${COINGECKO_API_KEY}
            - POSTGRES_URL=${POSTGRES_URL}
            - DATABASE_TYPE=supabase
            # - SUI_NETWORK=mainnet
            # - SUI_RPC_URL=https://fullnode.mainnet.sui.io:443
            # - SUI_FAUCET_URL=https://faucet.sui.io/
            # - SUI_FAUCET_KEY=
            # - SUI_FAUCET_AMOUNT=1000000000000000000
            # Refer to: https://github.com/elizaOS/eliza/blob/develop/.env.example for all available environment variables
        ports:
            - "3000:3000"
            - "5173:5173"
        restart: always

volumes:
    eliza:
